### ISSUE TITLE
Player/Tile Class Alterations

### ISSUE THREAD

**Issue by zmorgancs** [UNLV-CS472-672/2024-S-GROUP8-CW#17]
Tile

- Needs reference info (tile placement on board) for the player that owns specific tile

Player

- Needs reference to the tile that the player owns (either Vector2d position or reference to actual tile)
- Needs storage for Player's owned tiles.
- Implement AddTiles and RemoveTiles methods

**Comment by CodingAdam** [comment]
Closed with  #31
