### ISSUE TITLE
GUI Elements

### ISSUE THREAD

**Issue by CodingAdam** [UNLV-CS472-672/2024-S-GROUP8-CW#26]
- [ ] Inventory: 5 slots, bottom left corner, can discard card stacks 
- [ ] Turn Initiator: Simple, top right corner
- [ ] #51
- [ ] #46
- [ ] Players: Shows all players in game (Color and Name), middle right side

**Comment by CodingAdam** [comment]
Working on Inventory

**Comment by zmorgancs** [comment]
ill work on menu.

**Comment by Joeyo364** [comment]
I'll work on turn initiator and players.
