### ISSUE TITLE
Fix unbuildable scene

### ISSUE THREAD

**Issue by CodingAdam** [UNLV-CS472-672/2024-S-GROUP8-CW#45]
Building the project has a issue with a missing scene, breaking the pipeline and unity

**Comment by CodingAdam** [comment]
Btw I've fixed this on a branch of mine (probably not sure for certain), it'll be pushed along side the finished form of Inventory GUI

**Comment by GNAR1ZARD** [comment]
@CodingAdam Can we close?

**Comment by CodingAdam** [comment]
> @CodingAdam Can we close?

Yea sure
