### ISSUE TITLE
Escape Menu: Escape Menu, opening to exit game and settings, top left corner

### ISSUE THREAD

**Issue by zmorgancs** [UNLV-CS472-672/2024-S-GROUP8-CW#51]
Escape Menu GUI Implementation

## Summary
The player must have access to an escape menu during a match in the event that they need to pause, change settings or exit the game. The implementation of this feature should allow the player to either right click a "Menu" button located in the top left corner of the game screen, or press escape to toggle an escape menu on and off.

## Level of Importance
Very necessary. Almost all games have a way to pause during game play and either exit the game or change some settings so our game should also have this standard feature.

## Recommendations on Alternate Features
The escape menu could also display lifetime statistics (matches won, lifetime tiles captured, etc) for the players profile if we do any tracking of that.

## Context (Optional)
If the game is to have scalable resolution options then make sure that exit menu scales properly with different resolutions/aspect ratios and that the "Menu" button is always in the top left corner of the screen.

**Comment by CodingAdam** [comment]
Closed by #52
