### ISSUE TITLE
Inventory card selection system

### ISSUE THREAD

**Issue by GNAR1ZARD** [UNLV-CS472-672/2024-S-GROUP8-CW#75]
Inventory card selection system

- [x] Inventory Card Selection System
- [x] Create Attack System (Select Cards, push to a battle)
- [x] Create Defense System (Select Cards, finalize battle)

**Comment by CodingAdam** [comment]
Working on task Inventory Card Selection System

**Comment by nathalmg** [comment]
Working on Create Defense System

**Comment by zmorgancs** [comment]
Working on Create Attack System

**Comment by CodingAdam** [comment]
Closed by #104, #90, #102, #100
